service: aws-lambda-serverless

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: Global

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb